sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - iojs
  - "0.12"
before_install:
  - npm i -g npm@^2.0.0
  - npm install -g bower
  - bower install
  - npm install -g web-component-tester
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script:
  - npm prune
script: "wct"
after_success:
  - npm run semantic-release
